services:
  freesky:
    # Build from local repository Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 3001
        API_URL: http://192.168.3.148:3001
        BACKEND_PORT: 8005
    
    # Replace with actual container ID/name or comment out for default networking
    network_mode: "container:transmission-openvpn"
    
    # Ports are not needed when using container networking
    # Comment out if using container networking
    #ports:
    #  - "3001:3001"
    #  - "${BACKEND_PORT:-8005}:${BACKEND_PORT:-8005}"
    #  - "2019:2019"  # Expose Caddy admin port for debugging
    
    environment:
      # Application Configuration
      - PORT=3001
      - BACKEND_PORT=${BACKEND_PORT:-8005}
      - HOST_IP=${HOST_IP:-0.0.0.0}  # Dynamic host IP, will use 0.0.0.0 if not set
      - DOCKER_HOST_IP=192.168.3.148  # External hostname/IP for client-facing URLs
      - BACKEND_URI=${BACKEND_URI:-}  # Let rxconfig determine this dynamically
      - API_URL=http://192.168.3.148:3001  # Explicitly set for correct WebSocket connection
      
      # External Services
      - DADDYLIVE_URI=${DADDYLIVE_URI:-https://thedaddy.top}
      
      # Application Settings
      - PROXY_CONTENT=${PROXY_CONTENT:-TRUE}
      - SOCKS5=${SOCKS5:-}
      - WORKERS=${WORKERS:-2}  # Reduced from 3 to 2 workers
      - MAX_CONCURRENT_STREAMS=${MAX_CONCURRENT_STREAMS:-5}  # Reduced from 10 to 5
      
      # Reflex Framework Settings
      - REFLEX_ENV=prod
      - REFLEX_SKIP_COMPILE=1
      
      # Proxy Configuration
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
      - NO_PROXY=localhost,127.0.0.1
    
    # Resource Limits
    deploy:
      resources:
        limits:
          memory: 512M  # Reduced from 1G to 512M
        reservations:
          memory: 256M  # Reduced from 512M to 256M
    
    # Restart Policy
    restart: unless-stopped
    
    # Health Check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s