services:
  freesky:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8005:8005"
      - "2019:2019"  # Expose Caddy admin port for debugging
    environment:
      - PORT=3000
      - BACKEND_PORT=8005
      - BACKEND_URI=http://localhost:8005
      - API_URL=http://192.168.4.5:3000
      - DADDYLIVE_URI=https://thedaddy.click
      - PROXY_CONTENT=TRUE
      - SOCKS5=
      - WORKERS=3
      - REFLEX_ENV=prod
      - REFLEX_SKIP_COMPILE=1
      # Add proxy environment variables
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - NO_PROXY=localhost,127.0.0.1
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      freesky-network:
        aliases:
          - freesky
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  freesky-network:
    driver: bridge 